# Only load modules if they exist (uncomment if present)
#LoadModule proxy_module modules/mod_proxy.so
#LoadModule proxy_fcgi_module modules/mod_proxy_fcgi.so

# Do NOT include LoadModule slotmem_shm_module ... on Alpine

<IfModule proxy_module>
  ProxyRequests Off
  <Proxy *>
    Allow from all
  </Proxy>
</IfModule>